DEBUG 2020-09-28 13:40:57.023 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-09-28 13:40:57.024 UTC: 	 Running on: Linux lxplus782.cern.ch 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-09-28 13:40:57.024 UTC: 	 Executing command: 'status'
DEBUG 2020-09-28 13:40:57.024 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2020-09-28 13:40:57.025 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_ProtonReco_BTag-B-miniAOD2017_2020-09-28_UTC15-39-19/crab_BTag-B-miniAOD2017
ERROR 2020-09-28 13:40:57.025 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 627, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 489, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_ProtonReco_BTag-B-miniAOD2017_2020-09-28_UTC15-39-19/crab_BTag-B-miniAOD2017
INFO 2020-09-28 13:40:57.031 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-09-28 13:52:57.913 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-09-28 13:52:57.914 UTC: 	 Running on: Linux lxplus782.cern.ch 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-09-28 13:52:57.914 UTC: 	 Executing command: 'checkusername'
DEBUG 2020-09-28 13:52:57.915 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
WARNING 2020-09-28 13:52:57.916 UTC: 	 Warning: 'crab checkusername' command takes no arguments, 1 given. Ignoring arguments ['dmf'].
DEBUG 2020-09-28 13:52:57.922 UTC: 	 Checking credentials
DEBUG 2020-09-28 13:52:57.922 UTC: 	 Found proxy file /tmp/x509up_u30993
DEBUG 2020-09-28 13:52:57.922 UTC: 	 Getting proxy life time left
DEBUG 2020-09-28 13:52:58.529 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30993 -timeleft
 output : 39221

 error: 
 retcode : 0
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30993 -actimeleft
 output : 39220

 error: 
 retcode : 0
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Proxy lifetime 39221 secs is different from voms extension lifetime 39220 secs for proxy: /tmp/x509up_u30993
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Proxy valid for 10:53:40 hours
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Command use: checkusername
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Options use: ['dmf']
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Instance is None
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Server base url is None
DEBUG 2020-09-28 13:52:59.236 UTC: 	 Retrieving username ...
DEBUG 2020-09-28 13:52:59.237 UTC: 	 Retrieving username from CRIC...
DEBUG 2020-09-28 13:53:00.643 UTC: 	 username is dmf
INFO 2020-09-28 13:53:00.643 UTC: 	 Username is: dmf
DEBUG 2020-09-28 13:53:08.683 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-09-28 13:53:08.683 UTC: 	 Running on: Linux lxplus782.cern.ch 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-09-28 13:53:08.683 UTC: 	 Executing command: 'checkusername'
DEBUG 2020-09-28 13:53:08.683 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2020-09-28 13:53:08.689 UTC: 	 Checking credentials
DEBUG 2020-09-28 13:53:08.689 UTC: 	 Found proxy file /tmp/x509up_u30993
DEBUG 2020-09-28 13:53:08.689 UTC: 	 Getting proxy life time left
DEBUG 2020-09-28 13:53:09.295 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30993 -timeleft
 output : 39210

 error: 
 retcode : 0
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u30993 -actimeleft
 output : 39210

 error: 
 retcode : 0
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Proxy valid for 10:53:30 hours
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Command use: checkusername
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Options use: []
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Instance is None
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Server base url is None
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Retrieving username ...
DEBUG 2020-09-28 13:53:09.901 UTC: 	 Retrieving username from CRIC...
DEBUG 2020-09-28 13:53:10.749 UTC: 	 username is dmf
INFO 2020-09-28 13:53:10.750 UTC: 	 Username is: dmf
DEBUG 2020-09-28 13:53:34.423 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-09-28 13:53:34.423 UTC: 	 Running on: Linux lxplus782.cern.ch 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-09-28 13:53:34.423 UTC: 	 Executing command: 'getlog'
DEBUG 2020-09-28 13:53:34.423 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2020-09-28 13:53:34.433 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_ProtonReco_BTag-B-miniAOD2017_2020-09-28_UTC15-43-44/crab_BTag-B-miniAOD2017
ERROR 2020-09-28 13:53:34.433 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 627, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 489, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_ProtonReco_BTag-B-miniAOD2017_2020-09-28_UTC15-43-44/crab_BTag-B-miniAOD2017
INFO 2020-09-28 13:53:34.442 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-09-29 12:50:19.237 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-09-29 12:50:19.237 UTC: 	 Running on: Linux lxplus748.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-09-29 12:50:19.237 UTC: 	 Executing command: 'submit'
DEBUG 2020-09-29 12:50:19.238 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
INFO 2020-09-29 12:50:19.240 UTC: 	 Will use CRAB configuration file crab_data.py
DEBUG 2020-09-29 12:50:19.240 UTC: 	 Loading CRAB configuration file.
ERROR 2020-09-29 12:50:19.245 UTC: 	 Error while loading CRAB configuration:
name 'config' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-09-29 12:50:19.245 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'config' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-09-29 12:50:19.266 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-10-05 08:35:02.970 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-05 08:35:02.970 UTC: 	 Running on: Linux lxplus730.cern.ch 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-05 08:35:02.970 UTC: 	 Executing command: 'status'
DEBUG 2020-10-05 08:35:02.971 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2020-10-05 08:35:03.054 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_projects/crab_test
ERROR 2020-10-05 08:35:03.055 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 270, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 627, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 489, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_projects/crab_test
INFO 2020-10-05 08:35:03.078 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-10-05 09:26:02.880 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-05 09:26:02.881 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-05 09:26:02.881 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-05 09:26:02.882 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
INFO 2020-10-05 09:26:02.883 UTC: 	 Will use CRAB configuration file crab-bjet.py
DEBUG 2020-10-05 09:26:02.883 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-05 09:26:02.884 UTC: 	 Error while loading CRAB configuration:
unexpected indent (crab-bjet.py, line 6)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-05 09:26:02.884 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
unexpected indent (crab-bjet.py, line 6)
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-05 09:26:02.888 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-10-05 09:27:08.496 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-05 09:27:08.496 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-05 09:27:08.496 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-05 09:27:08.496 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
INFO 2020-10-05 09:27:08.497 UTC: 	 Will use CRAB configuration file crab-bjet.py
DEBUG 2020-10-05 09:27:08.497 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-05 09:27:08.500 UTC: 	 Error while loading CRAB configuration:
name 'timestr' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-05 09:27:08.501 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'timestr' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-05 09:27:08.502 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-10-05 09:28:41.247 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-05 09:28:41.247 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-05 09:28:41.247 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-05 09:28:41.248 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
INFO 2020-10-05 09:28:41.249 UTC: 	 Will use CRAB configuration file crab-bjet.py
DEBUG 2020-10-05 09:28:41.249 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-05 09:28:41.253 UTC: 	 Error while loading CRAB configuration:
name 'RunMissingMassSearches' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-05 09:28:41.253 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'RunMissingMassSearches' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-05 09:28:41.254 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2020-10-05 09:41:27.893 UTC: 	 CRAB Client version: v3.200812
DEBUG 2020-10-05 09:41:27.894 UTC: 	 Running on: Linux lxplus731.cern.ch 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-10-05 09:41:27.894 UTC: 	 Executing command: 'submit'
DEBUG 2020-10-05 09:41:27.894 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
INFO 2020-10-05 09:41:27.895 UTC: 	 Will use CRAB configuration file crab-bjet.py
DEBUG 2020-10-05 09:41:27.895 UTC: 	 Loading CRAB configuration file.
ERROR 2020-10-05 09:41:27.899 UTC: 	 Error while loading CRAB configuration:
name 'pathfull' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-10-05 09:41:27.899 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 311, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.200812.00/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'pathfull' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-10-05 09:41:27.903 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-01-06 11:51:31.165 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-06 11:51:31.165 UTC: 	 Running on: Linux lxplus7114.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-06 11:51:31.165 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-06 11:51:31.177 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-01-06 17:49:01.860 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-06 17:49:01.860 UTC: 	 Running on: Linux lxplus7114.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-06 17:49:01.860 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-06 17:49:01.870 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-01-06 17:51:37.016 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-06 17:51:37.016 UTC: 	 Running on: Linux lxplus7114.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-06 17:51:37.016 UTC: 	 Executing command: 'status'
DEBUG 2021-01-06 17:51:37.017 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-01-06 17:51:37.018 UTC: 	 Error: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-06_UTC18-4 is not a valid CRAB project directory.
ERROR 2021-01-06 17:51:37.018 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-06_UTC18-4 is not a valid CRAB project directory.
INFO 2021-01-06 17:51:37.020 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-01-07 09:53:31.838 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-07 09:53:31.838 UTC: 	 Running on: Linux lxplus746.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-07 09:53:31.838 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-07 09:53:31.849 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-01-07 12:26:06.861 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-07 12:26:06.861 UTC: 	 Running on: Linux lxplus746.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-07 12:26:06.861 UTC: 	 Executing command: 'status'
DEBUG 2021-01-07 12:26:06.862 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-01-07 12:26:06.864 UTC: 	 Error: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-5 is not a valid CRAB project directory.
ERROR 2021-01-07 12:26:06.864 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-5 is not a valid CRAB project directory.
INFO 2021-01-07 12:26:06.911 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-01-07 12:36:31.707 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-07 12:36:31.707 UTC: 	 Running on: Linux lxplus746.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-07 12:36:31.707 UTC: 	 Executing command: 'status'
DEBUG 2021-01-07 12:36:31.708 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-01-07 12:36:31.712 UTC: 	 Error: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-5 is not a valid CRAB project directory.
ERROR 2021-01-07 12:36:31.712 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-5 is not a valid CRAB project directory.
INFO 2021-01-07 12:36:31.747 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-01-07 12:37:37.409 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-07 12:37:37.410 UTC: 	 Running on: Linux lxplus746.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-07 12:37:37.410 UTC: 	 Executing command: 'status'
DEBUG 2021-01-07 12:37:37.410 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-01-07 12:37:37.411 UTC: 	 Error: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-5 is not a valid CRAB project directory.
ERROR 2021-01-07 12:37:37.411 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-5 is not a valid CRAB project directory.
INFO 2021-01-07 12:37:37.414 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-01-07 14:32:27.654 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-07 14:32:27.654 UTC: 	 Running on: Linux lxplus746.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-07 14:32:27.654 UTC: 	 Executing command: 'status'
DEBUG 2021-01-07 14:32:27.654 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-01-07 14:32:27.678 UTC: 	 Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/d/dmf/private/work/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-52-31/crab_signal-hx-PostTS2-120-miniAOD2017
ERROR 2021-01-07 14:32:27.679 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 632, in validateOptions
    self.loadLocalCache()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 494, in loadLocalCache
    raise ex
CachefileNotFoundException: Cannot find .requestcache file in CRAB project directory /afs/cern.ch/user/d/dmf/private/work/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_ProtonReco_signal-hx-PostTS2-120-miniAOD2017_2021-01-07_UTC10-52-31/crab_signal-hx-PostTS2-120-miniAOD2017
INFO 2021-01-07 14:32:27.777 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-01-22 08:34:21.750 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-22 08:34:21.750 UTC: 	 Running on: Linux lxplus796.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-22 08:34:21.750 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-22 08:34:21.781 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-01-22 08:34:21.829 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
DEBUG 2021-01-22 08:43:19.507 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-22 08:43:19.507 UTC: 	 Running on: Linux lxplus796.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-22 08:43:19.507 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-22 08:43:19.551 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-01-22 08:52:39.871 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-22 08:52:39.871 UTC: 	 Running on: Linux lxplus796.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-22 08:52:39.871 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-22 08:52:39.889 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-01-29 13:52:30.379 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-01-29 13:52:30.379 UTC: 	 Running on: Linux lxplus783.cern.ch 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-01-29 13:52:30.379 UTC: 	 Executing command: 'submit'
DEBUG 2021-01-29 13:52:30.380 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
DEBUG 2021-02-01 08:58:18.372 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-01 08:58:18.372 UTC: 	 Running on: Linux lxplus759.cern.ch 3.10.0-1160.2.2.el7.x86_64 #1 SMP Tue Oct 20 16:53:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-01 08:58:18.372 UTC: 	 Executing command: 'status'
DEBUG 2021-02-01 08:58:18.372 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-02-01 08:58:18.374 UTC: 	 Error: /afs/cern.ch/user/d/dmf/private/work/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_/* is not a valid CRAB project directory.
ERROR 2021-02-01 08:58:18.374 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: Error: /afs/cern.ch/user/d/dmf/private/work/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab_/* is not a valid CRAB project directory.
INFO 2021-02-01 08:58:18.396 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-02-03 10:29:00.203 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-03 10:29:00.203 UTC: 	 Running on: Linux lxplus790.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-03 10:29:00.204 UTC: 	 Executing command: 'kill'
DEBUG 2021-02-03 10:29:00.204 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
ERROR 2021-02-03 10:29:00.207 UTC: 	 Error: all is not a valid CRAB project directory.
ERROR 2021-02-03 10:29:00.208 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 271, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.201110.01/lib/CRABClient/Commands/SubCommand.py", line 628, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: all is not a valid CRAB project directory.
INFO 2021-02-03 10:29:00.226 UTC: 	 Log file is /afs/cern.ch/work/d/dmf/private/CMSPhysicsAnalysis/DarkMatterSearch/NTuplizer/devel/CMSSW_10_6_0/src/MissingMass/Skimmer/test/crab.log
DEBUG 2021-02-03 10:46:09.003 UTC: 	 CRAB Client version: v3.201110
DEBUG 2021-02-03 10:46:09.003 UTC: 	 Running on: Linux lxplus790.cern.ch 3.10.0-1160.6.1.el7.x86_64 #1 SMP Tue Nov 17 13:59:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2021-02-03 10:46:09.003 UTC: 	 Executing command: 'submit'
DEBUG 2021-02-03 10:46:09.004 UTC: 	 Found CRAB cache file /afs/cern.ch/user/d/dmf/.crab3
